[package]
name = "picopub"
version = "0.1.0"
authors = ["Nathan Yergler <nathan@yergler.net>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"

serde_urlencoded = "0.5"
serde_json = "1.0"
